# **Módulo 1: Introducción y entorno de trabajo**

## **1.5 Introducción a la manipulación de datos: Creación, manipulación y análisis de datos tabulares**

In [26]:
# Crear un diccionario
data={
    "Nombre":["María","Ana", "Pedro", "Juan", "Carlos", "Sara"], # Lista de nombres se plantea con corchetes
    "Edad":[21,22,19,26,22,19], # Lista de edades se plantea con corchetes
    "Género":["F","F","M","M","M","F"] # Lista de género se plantea con corchetes
}

# Imprimir data
print(data)

{'Nombre': ['María', 'Ana', 'Pedro', 'Juan', 'Carlos', 'Sara'], 'Edad': [21, 22, 19, 26, 22, 19], 'Género': ['F', 'F', 'M', 'M', 'M', 'F']}

2. Importemos el módulo __pandas__:

In [27]:
# Libreria
import pandas as pd

3. Convertimos el diccionario en un __DataFrame__:

In [28]:
# DataFrame es una función que está dentro del módulo pandas

df = pd.DataFrame(data)

### **1.5.2 Manipulación de datos**

In [29]:
# Obtener información sobre la estructura del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  6 non-null      object
 1   Edad    6 non-null      int64
 2   Género  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 272.0+ bytes

In [30]:
# Obtener las dimensiones del DataFrame

df.shape

(6, 3)

In [31]:
# Mostrar las 5 primeras filas del DataFrame
df.head()

# Mostrar las 2 primeras filas del DataFrame
df.head(n=2)

  Nombre  Edad Género
0  María    21      F
1    Ana    22      F

In [32]:
# Mostrar las 5 ultimas filas de DataFrame
df.tail()

# Mostrar las 3 ultimas filas de DataFrame
df.tail(n=3)

   Nombre  Edad Género
3    Juan    26      M
4  Carlos    22      M
5    Sara    19      F

In [33]:
df.columns

Index(['Nombre', 'Edad', 'Género'], dtype='object')

In [34]:
# Renombrar las columnas del DataFrame
df.columns = ['Nombre_Cliente', 'Edad_Cliente', 'Genero_Cliente']

In [35]:
# Obtener el índice del DataFrame
df.columns

Index(['Nombre_Cliente', 'Edad_Cliente', 'Genero_Cliente'], dtype='object')

In [36]:
df.index = ['a', 'b', 'c', 'd', 'e', 'f']
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [39]:
df.head()

  Nombre_Cliente  Edad_Cliente Genero_Cliente
a          María            21              F
b            Ana            22              F
c          Pedro            19              M
d           Juan            26              M
e         Carlos            22              M

In [38]:
# Ordenar el DataFrame df por la columna 'Edad' en orden descendente

df.sort_values(by='Edad_Cliente', ascending=False)

  Nombre_Cliente  Edad_Cliente Genero_Cliente
d           Juan            26              M
b            Ana            22              F
e         Carlos            22              M
a          María            21              F
c          Pedro            19              M
f           Sara            19              F

In [51]:
# Seleccionar la primera fila (índice 0)
df.iloc[0]

# Seleccionar las primeras tres filas
df.iloc[0:3]

# Seleccionar el valor en la primera fila y segunda columna
df.iloc[0, 1]

# Seleccionar las primeras dos filas y las primeras tres columnas
df.iloc[0:2, 0:3]

# Seleccionar todos los valores de la segunda columna
df.iloc[:,1]

# Seleccionar las últimas dos filas de todas las columnas
df.iloc[-2:]

# Seleccionar las columnas por su nombre
df['Nombre_Cliente']

# Otra forma de seleccionar las columnas por su nombre
df.Nombre_Cliente

# Seleccionar el valor en la primera fila como un DataFrame
df.iloc[[0],:]

# Seleccionar las filas 1 y 3 como un DataFrame
df.iloc[[1,3],:]

# Seleccionar las columnas 1 y 3 como un DataFrame
df.iloc[:,[0,2]]

  Nombre_Cliente Genero_Cliente
a          María              F
b            Ana              F
c          Pedro              M
d           Juan              M
e         Carlos              M
f           Sara              F

Este método es clave para acceder y manipular datos en un DataFrame utilizando posiciones, especialmente cuando los índices o nombres de columnas no son intuitivos o cuando estás realizando operaciones sobre DataFrames grandes y complejos.

* El método `df.loc` en Pandas se utiliza para acceder a un DataFrame por etiquetas de filas y columnas, a diferencia de `iloc`, que usa posiciones numéricas. `loc` permite una variedad de operaciones para seleccionar y filtrar datos basados en las etiquetas de los índices y columnas. Por ejemplo:

In [59]:
# Seleccionar la fila con la etiqueta 'b'
df.loc['b']

# Seleccionar las filas con etiquetas de 'a' a 'c' (inclusive)
df.loc['a':'c']

# Seleccionar el valor en la fila con etiqueta 'b' y columna 'Edad'
df.loc['b', 'Edad_Cliente']

# Seleccionar las filas 'a' a 'c' y las columnas 'Nombre' y 'Edad'
df.loc['a':'c', ['Nombre_Cliente', 'Edad_Cliente']]

# Seleccionar todas las filas y solo la columna 'Genero'
df.loc[:, 'Genero_Cliente']

# Seleccionar todas las filas donde 'Edad' es mayor que 25
df.loc[df['Edad_Cliente'] > 25, ['Nombre_Cliente', 'Genero_Cliente']]

  Nombre_Cliente Genero_Cliente
d           Juan              M

## **1.6 Importación de datos**

Ahora importemos un archivo plano con `Pandas`:

In [64]:
import pandas as pd

# Importar un archivo CSV como DataFrame
filename = '_data/winequality-red.csv'
data = pd.read_csv(filename, sep=';')  # Asegúrate de usar el separador correcto si es necesario

# Ver las primeras 5 filas del DataFrame
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [65]:
data_array = data.to_numpy()
data_array

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [66]:
# Crear un DataFrame
data = {
    'Columna1': [1, 4, 7],
    'Columna2': [2, 5, 8],
    'Columna3': [3, 6, 9]
}
df = pd.DataFrame(data)

# Guardar el DataFrame en un archivo CSV
df.to_csv('output.csv', index=False)  # index=False para no guardar el índice en el archivo CSV

### **1.6.2. Importación y exportación de datos serializados**

In [75]:
import pickle

filename = '_data/data_fruta.pkl'

with open(filename,'rb') as file:
    data = pickle.load(file)

print(data)

{'apple': 10, 'banana': 20, 'cherry': 30}

In [74]:
import joblib

data = joblib.load('_data/data_fruta.pkl')
print(data)

{'apple': 10, 'banana': 20, 'cherry': 30}

In [76]:
# Crear un objeto (por ejemplo, un diccionario)
data = {'a': 1, 'b': 2, 'c': 3}

# Guardar el objeto en un archivo pickle
with open('_data/archivo_2.pkl', 'wb') as file:
    pickle.dump(data, file)

In [72]:
import joblib

# Crear un objeto (por ejemplo, un diccionario)
data = {'a': 1, 'b': 2, 'c': 3}

# Guardar el objeto en un archivo pickle
joblib.dump(data, '_data/archivo_2-joblib.pkl')

['_data/archivo_2-joblib.pkl']

### **1.6.3. Importación y exportación de datos en Excel**

Debemos instalar en el terminal con el environment activo, la siguiente instrucción `pip install openpyxl`

In [84]:
import pandas as pd
df = pd.read_excel('_data/urbanpop.xlsx', sheet_name='1960-1966')
df.head()

,country,1960,1961,1962,1963,1964,1965,1966
0,Afghanistan,769308.0,8.149230e+05,8.585217e+05,9.039139e+05,9.512259e+05,1.000582e+06,1.058743e+06
1,Albania,494443.0,5.118028e+05,5.294389e+05,5.473767e+05,5.655718e+05,5.839829e+05,6.025122e+05
2,Algeria,3293999.0,3.515148e+06,3.739963e+06,3.973289e+06,4.220987e+06,4.488176e+06,4.649105e+06
3,American Samoa,NaN,1.366030e+04,1.416580e+04,1.475893e+04,1.539642e+04,1.604482e+04,1.669311e+04
4,Andorra,NaN,8.723921e+03,9.700346e+03,1.074838e+04,1.186586e+04,1.305275e+04,1.421681e+04

In [ ]:
# ver hojas de un archivo Excel sin abrirlo
filename = '_data/urbanpop.xlsx'
data = pd.ExcelFile(filename)
data.sheet_names

['1960-1966', '1967-1974', '1975-2011']

O si prefieres usar el índice de la hoja:

In [89]:
# Lee la primera hoja (índice 0) del archivo Excel
df = pd.read_excel('_data/urbanpop.xlsx', sheet_name=0)
df.head()

,country,1960,1961,1962,1963,1964,1965,1966
0,Afghanistan,769308.0,8.149230e+05,8.585217e+05,9.039139e+05,9.512259e+05,1.000582e+06,1.058743e+06
1,Albania,494443.0,5.118028e+05,5.294389e+05,5.473767e+05,5.655718e+05,5.839829e+05,6.025122e+05
2,Algeria,3293999.0,3.515148e+06,3.739963e+06,3.973289e+06,4.220987e+06,4.488176e+06,4.649105e+06
3,American Samoa,NaN,1.366030e+04,1.416580e+04,1.475893e+04,1.539642e+04,1.604482e+04,1.669311e+04
4,Andorra,NaN,8.723921e+03,9.700346e+03,1.074838e+04,1.186586e+04,1.305275e+04,1.421681e+04

In [90]:
# Lee las hojas '1960–1966' y '1975–2011' del archivo Excel
sheets = pd.read_excel('_data/urbanpop.xlsx',
                       sheet_name=['1960-1966',
                                   '1975-2011'])

# Accede a cada DataFrame por el nombre de la hoja
df1 = sheets['1960-1966']
df2 = sheets['1975-2011']

In [91]:
df_total = pd.concat([df1, df2], ignore_index=True)

In [92]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 45 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  418 non-null    object
 1   1960     198 non-null    float64
 2   1961     209 non-null    float64
 3   1962     209 non-null    float64
 4   1963     209 non-null    float64
 5   1964     209 non-null    float64
 6   1965     209 non-null    float64
 7   1966     209 non-null    float64
 8   1975     209 non-null    float64
 9   1976     209 non-null    float64
 10  1977     209 non-null    float64
 11  1978     209 non-null    float64
 12  1979     209 non-null    float64
 13  1980     209 non-null    float64
 14  1981     209 non-null    float64
 15  1982     209 non-null    float64
 16  1983     209 non-null    float64
 17  1984     209 non-null    float64
 18  1985     209 non-null    float64
 19  1986     209 non-null    float64
 20  1987     209 non-null    float64
 21  1988     209 non-null    float64
 22  1989     209 non-null    float64
 23  1990     209 non-null    float64
 24  1991     209 non-null    float64
 25  1992     208 non-null    float64
 26  1993     208 non-null    float64
 27  1994     208 non-null    float64
 28  1995     209 non-null    float64
 29  1996     209 non-null    float64
 30  1997     209 non-null    float64
 31  1998     209 non-null    float64
 32  1999     209 non-null    float64
 33  2000     209 non-null    float64
 34  2001     209 non-null    float64
 35  2002     209 non-null    float64
 36  2003     209 non-null    float64
 37  2004     209 non-null    float64
 38  2005     209 non-null    float64
 39  2006     209 non-null    float64
 40  2007     209 non-null    float64
 41  2008     209 non-null    float64
 42  2009     209 non-null    float64
 43  2010     209 non-null    float64
 44  2011     209 non-null    float64
dtypes: float64(44), object(1)
memory usage: 147.1+ KB

In [93]:
# Crear un DataFrame
data = {
    'Columna1': [1, 4, 7],
    'Columna2': [2, 5, 8],
    'Columna3': [3, 6, 9]
}
df = pd.DataFrame(data)

# Guardar el DataFrame en un archivo Excel
df.to_excel('_data/columnas-excel.xlsx', index=False)  # index=False para no guardar el índice en el archivo Excel

## **1.7. Manipulación de datos con pandas**

In [1]:
import pandas as pd
import numpy as np

Carguemos el conjunto de datos de **marketing del banco** `bank-full`. 

Los datos están relacionados con `campañas de marketing directo` (llamadas telefónicas) de una institución bancaria portuguesa.

Este conjunto de datos tiene 4521 observaciones y 17 variables. Las variables son:

* **age:** Edad del cliente.
* **job**: Profesión del cliente (por ejemplo, desempleado, servicios, gestión).
* **marital**: Estado civil del cliente (soltero, casado, divorciado).
* **education**: Nivel educativo del cliente (primaria, secundaria, terciaria).
* **default** : Indica si el cliente tiene crédito en incumplimiento (sí o no).
* **balance**: Saldo promedio anual de la cuenta bancaria del cliente.
* **housing**: Indica si el cliente tiene un préstamo hipotecario (sí o no).
* **loan**: Indica si el cliente tiene un préstamo personal (sí o no).
* **contact**: Tipo de comunicación de contacto (teléfono celular, teléfono fijo).
* **day**: Día del mes en que se realizó el último contacto con el cliente.
* **month**: Mes en que se realizó el último contacto con el cliente.
* **duration**: Duración del último contacto en segundos.
* **campaign**: Número de contactos realizados durante esta campaña de marketing.
* **pdays**: Días que han pasado desde que el cliente fue contactado por última vez en una campaña anterior (valores -1 indican que el cliente no fue contactado previamente).
* **previous**: Número de contactos realizados antes de esta campaña.
* **poutcome**: Resultado de una campaña de marketing anterior (éxito, fracaso, desconocido).
* **y**: Resultado de la campaña actual (si el cliente suscribió o no un depósito a plazo fijo).

In [ ]:
# Asignar la URL del archivo: url
url =# TU CODIGO AQUI

# leer el archivo en u dataframe:df
df = pd.read_csv(url,sep=';')

# Imprimir el encabezado del dataframe
# TU CODIGO AQUI

# Mostrar las 5 ultimas filas de DataFrame
# TU CODIGO AQUI

# Concatenar el encabezado y las últimas 5 filas del DataFrame
#result = # TU CODIGO AQUI
#print(result)

Las dimensiones del dataset:

In [ ]:
# Obtener las dimensiones del DataFrame
# TU CODIGO AQUI

Información de la estructura del dataset de marketing:

In [ ]:
# Obtener información sobre la estructura del DataFrame
# TU CODIGO AQUI

El atributo `df.size` en pandas devuelve el número total de elementos en un `DataFrame`. Esto se calcula multiplicando el número de filas por el número de columnas. Es útil para obtener una visión rápida del tamaño total del DataFrame en términos de elementos.

In [ ]:
# número total de elementos en el dataframe
# TU CODIGO AQUI

Puede ocurrir que el conjunto de datos de marketing para la banca tenga duplicados. El método `drop_duplicates()` en pandas se utiliza para eliminar filas duplicadas de un DataFrame. Este método permite identificar y remover filas que contienen los mismos valores en las columnas seleccionadas, o en todas las columnas si no se especifica ninguna.

In [ ]:
# Eliminar filas duplicadas
df = # TU CODIGO AQUI
df.info()

Ahora, el nombres de las variables, el indice, el tipo de dato del dataset de marketing

In [ ]:
# nombre de las variables
# TU CODIGO AQUI

# Obtener el índice del DataFrame
# TU CODIGO AQUI

# tipo de dato
# tu codigo aquí

Queremos saber los clientes menores de 20 años:

In [ ]:
# Seleccionar solo las filas donde la condición es True
# TU CODIGO AQUI

# Mostrar los clientes menores de 20 años
# TU CODIGO AQUI

# imprimir el dataframe las 5 primeras
# dfm20.head()

Escojamos las columnas `age`, `marital`, `balance`, `y` de los clientes menores de 20

In [ ]:
# seleccionemos las columnas
new_dfm20 = # TU CODIGO AQUI

# imprimir
print(new_dfm20.head())

In [ ]:
# ordenar
new_dfm20.sort_values(by='balance', ascending=False)

Puedes aplicar una función personalizada a una columna específica del DataFrame usando el método `apply()` de `pandas`. Supongamos que deseas crear una nueva columna llamada `balance_category` que clasifique el balance de cada cliente en `"Bajo"`, `"Medio"` o `"Alto"` según ciertos umbrales.

In [18]:
# Definir una función para categorizar el balance
def categorizar_balance(balance):
    if balance < 500:
        return 'Bajo'
    elif 500 <= balance < 1500:
        return 'Medio'
    else:
        return 'Alto'

In [ ]:
# Aplicar la función 'categorizar_balance' a la columna 'balance'
# y crear la nueva columna 'balance_category'
new_dfm20.loc[:,'balance_category'] = # TU CODIGO AQUI

# Mostrar el DataFrame actualizado
print(new_dfm20.head())

Ahora, debemos obtener los clientes menores de 20 que si se suscribieron. Ademas los que se suscribieron con balance bajo.

In [ ]:
# menores de 20 que se suscribieron
# TU CODIGO AQUI

# Otra forma de seleccionarlos
new_dfm20[new_dfm20['y'].isin(['yes'])]

# menores de 20 que se suscribieron con balance bajo
# TU CODIGO AQUI

#### **Adición de nuevas columnas al DataFrame**

In [ ]:
new_dfm20.loc[:,'balance_por_age'] = # TU CODIGO AQUI
print(new_dfm20.head())

* Ahora, veremos la adición condicional de columnas. Vamos a intentar añadir una columna basada en el valor de la edad, digamos que todo lo que sea más de 17 como mayor de edad (codificado como 1) y todo lo que sea inferior a 17 como menor de edad (codificado como 0).

In [ ]:
new_dfm20.loc[:,'age_cat'] = # tu codigo aquí
print(new_dfm20.tail())

#### **Indices explicitos**

Analicemos algunas funciones utiles de la indexación explicita:

* `df.set_index()`; Este método se usa para establecer una o más columnas del DataFrame como su índice.

In [ ]:
# Establecer la columna 'job' como índice
# tu codigo aquí

* `df.reset_index()`:Este método se usa para restablecer el índice del DataFrame, devolviendo los índices actuales a columnas y creando un nuevo índice numérico predeterminado. Si usas el parámetro `drop=True` indica que se debe eliminar la columna de índice original en lugar de moverla a una columna.

In [ ]:
# tu codigo aquí

* `df.sort_index()`: Este método ordena las filas del DataFrame en función del índice.

In [ ]:
# orden de los indices
# tu codigo aquí

En conclusión, el uso de índices explícitos en Python es una técnica poderosa que permite un control detallado sobre la manipulación de datos. Ya sea en estructuras simples como listas o en análisis más complejos utilizando pandas, el conocimiento y uso adecuado de índices explícitos puede mejorar significativamente la eficiencia y claridad de tu código.